modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "netherite_ext"
version = "${version}"
displayName = "Netherite Extension"
authors = "IAFEnvoy"
description = '''
The high version port of Netherite Plus Mod
Add more netherite items into game.
'''
logoFile = "logo.jpg"

[[dependencies.netherite_ext]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherite_ext]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netherite_ext]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
